config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments
  end
  
  root "posts#index"

  get '/about', to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :comments 
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_comment, only: [:create, :destroy]    
    before_action :comment_auth, only: [:destroy]    


	def create
	  @post = Post.find(params[:post_id])
	  @comment = @post.comments.create(params[:comment].permit(:name, :body))
	  @comment.user_id = current_user.id if current_user
	  @comment.save

	  if @comment.save!
	    redirect_to post_path(@post)
	  else
	    render 'new'
	  end
	end  

    def destroy    
        @comment = @post.comments.find(params[:id]).destroy    
        redirect_to post_path(@post)   
    end    

    private    

	    def comment_params    
	        params.require(:comment).permit(:user_id, :name, :body)    
	    end   

	    def find_comment    
	        @post = Post.find(params[:post_id])    
	    end   

	    def comment_auth    
	        if current_user != @post.user    
	        redirect_to(root_path)   
	        end    
    	end
end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end

	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]       
    before_action :authenticate_user!, except: [:index, :show]    
    before_action :post_auth, only: [:edit, :update, :destroy]
	
	def index
		@posts = Post.all.order("created_at DESC")
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	  	@user = current_user 
	end

	def edit
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render "edit"
		end		
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private
	
		def post_params
			params.require(:post).permit(:title, :body)
		end

		def find_post
			@post = Post.find(params[:id])
		end

		def post_auth
			if current_user != @post.user
				redirect_to(root_path)
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>
	</div>

		<% if current_user %>
		<p><%= link_to "Delete", [comment.post, comment],
						method: :delete,
						class: "button",
						data: {confirm: "Are you sure?"} %>
		</p>
		<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %> 
	</p>

	<p>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KiNG BLOG!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <link rel="shortcut icon" href="assets/logo_k-8d3b052b541580a96e5dc7a2814b47d214835b328a2c8274184f11f84363ec3e.png">
  <body>
  	<div id="sidebar">
  		<div class="logo">
  			<%= link_to root_path do %>
  				<%= image_tag "logo_k.png" %>
  			<% end %>
  		</div>

  		<ul>
  			<li class="category">KiNG BLOG</li>
  			<li><%= link_to "Blog", root_path %></li>
  			<li><%= link_to "About", about_path %></li>
  		</ul>

        <% if !user_signed_in? %>
  			<p class="sign_in">Admin Login</p>
        <% end %>
  	</div>

  	<div id="main_content">
  		<div id="header">

  			<% if user_signed_in? %>
  			<% else %>
  				<%= link_to "Log in", new_user_session_path %> &nbsp&nbsp
  				<%= link_to "Sign up", new_user_registration_path %> &nbsp&nbsp
  			<% end %>
  		
			<% if current_page?(root_path) %>
  				<p>All Posts</p>
          	<% elsif current_page?(about_path) %>
            	<p>About</p>
          	<% else %>
            	<%= link_to "Back to All Posts", root_path %>
          	<% end %>
  				
          	<% if user_signed_in? %>
    			<div class="buttons">
    				<button class="button"><%= link_to "New Post", new_post_path %></button>
    				<button class="button"><%= link_to("Log Out", destroy_user_session_path, method: :delete) %>﻿</button>
    			</div>
          	<% end %>
		</div>

  	<%= yield %>

  	</div>	
    
  
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "NYE.jpg" %>
	</div>

	<div id="content">
		<h1>Welcome to KiNG BLOG!</h1>
		<h2>I'm Paul Elion, the creator of KiNG BLOG.</h2>
		<p>"For centuries, writers have experimented with forms that evoke the imperfection of thought, the inconstancy of human affairs, and the chastening passage of time. But as blogging evolves as a literary form, it is generating a new and quintessentially postmodern idiom that’s enabling writers to express themselves in ways that have never been seen or understood before. Its truths are provisional, and its ethos collective and messy. Yet the interaction it enables between writer and reader is unprecedented, visceral, and sometimes brutal. And make no mistake: it heralds a golden era for journalism.</p>
		<h3>....and no place embodies that more so than KiNG BLOG." <br><br> - Barrack Obama</h3>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><% msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %>
		</p>

		<p>
			<%= f.submit %>
		</p>

	<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
	</div>

<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago
		 <%= link_to "Edit", edit_post_path(@post) %>
		 <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
	</p>

	<p class="body">
		<%= @post.body %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>
	<% if current_user %>
		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	<% end %>
	</div>
</div>